project:
  type: website
  output-dir: docs

website:
  title: "French FastPitch HiFiGAN G2P"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Notebooks
        href: notebooks/fastpitch-hifigan-demo.ipynb
format:
  html:
    theme: cosmo
    toc: true
